name: test_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0  # для определения координат
  http: ^0.13.0        # для запроса к API
  google_maps_flutter: ^2.6.0
 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0



flutter:

 
  uses-material-design: true

 